### ISSUE TITLE
if语句的判断条件写反了吧？

### ISSUE THREAD

**Issue by lyx9439** [Tencent/WeComponents#1]
src/components/input/input.vue文件的507行，感觉应该是
if (this.dblClickEventName === 'onInputDblClick')
原因：若未自定义(this.dblClickEventName === 默认值)，则执行默认行为（this._editable()）

![image](https://user-images.githubusercontent.com/25003211/69033767-a876b200-0a1a-11ea-9f58-3f37af5744b8.png)

**Comment by NaibinJi** [comment]
感谢提醒，这里修改了readonly属性的交互逻辑后，对应双击事件逻辑的修改遗漏了，马上修复

**Comment by damonpeng** [comment]
fixed at v2.0.9，感谢反馈
