### ISSUE TITLE
建议：1. validity支持自定义方法  2.show/hide 支持自定义方法

### ISSUE THREAD

**Issue by TonyLuo** [Tencent/WeComponents#10]
1. validity支持自定义方法  
目前的校验比较简单，没办法支持复杂的校验规则，特别是组件之间有联动关系的校验
2.show/hide 支持自定义方法
有些组件涉及到权限控制，建议用自定义的visible 方法返会true/false决定是否显示组件

**Comment by damonpeng** [comment]
1.

**Comment by damonpeng** [comment]
@TonyLuo 
1. 麻烦举个具体的例子，我们分析下
2. 因界面本身是数据驱动，所以需要按照你的具体场景，把权限控制的逻辑，和对数据内容的改变联动起来。show/hide，除了在attributes直接设置外，还提供了快捷方法，如 this.page.show(id)/this.page.hide(id)，不知是否可满足需求。如不满足，可以说下具体例子。

**Comment by TonyLuo** [comment]
1、attributes.hide 、 attributes.disabled、attributes.readonly 这些属性可以让他们同时支持boolean和function，这样可以更加灵活根据不同的业务实现自己的hide或者disabled的逻辑。

2、validity.required也是同样的道理。 建议加上validity.verify支持自定义的校验方法。

3、this.page.show(id)/this.page.hide(id)能满足一部分需求，但维护整个页面的组件ID唯一性是一个很麻烦的事情
4、table组件的table items （我觉得叫columns可能更合适）hide的属性建议也支持自定义方法，让开发者根据自己的逻辑判断是否需要隐藏某些列

**Comment by TonyLuo** [comment]
另外，建议起一个 development分支，把正在开发的也开源出来，让社区感兴趣的人可以参与进来一起改进

**Comment by damonpeng** [comment]
1. 虽然这样很不“声明式”，但在易用角度上是可以接受的，尤其是JS本身泛型的支持。
2. ok

**Comment by damonpeng** [comment]
1. 虽然这样很不“声明式”，但在易用角度上是可以接受的，尤其是JS本身泛型的支持。
2. ok
3. 同1
4. 叫items是从数据描述这个角度出发来说的，且不同组件的数据结构是一致的，不会因为表现不同（table），而更改结构

**Comment by damonpeng** [comment]
> 另外，建议起一个 development分支，把正在开发的也开源出来，让社区感兴趣的人可以参与进来一起改进

好建议，这里的组织方式（内外版本同步）上，内部先讨论下。期待你参与贡献。

**Comment by TonyLuo** [comment]
清明假期雨纷纷，困在家里发霉。索性多提几个想法：
1、组件的继承问题。一般来说，每个页面导航栏，页眉，页尾这些都是不变的，你们建议的最佳实践是什么？是每个页面都写一个container，每个container里面的导航栏，页眉，页尾都重复写一遍？还是可以通过继承container解决？
2、是否可以通过指定一个页面里面某些地方才渲染WeComponents? 其他地方留给开发人员自由发挥，可以定制自己的页面风格。

例如：
```html
<html>
<head>
my customized header
</header>
<body>
<div>
my customized content 1
</div>

<div id="WeComponentsContent">
<!-- render WeComponents content-->
</div>

<div>
my customized content 2
</div>

</body>
<footer>
my customized footer
</footer>
<html>

```

**Comment by damonpeng** [comment]
珍惜可以发霉的时光。
1. 导航栏、页眉、页尾直接在App.vue搞定，页面逻辑不需要操心页面框架的东西。
2. 之前有讨论过，也就是混用传统开发模式，考虑过类似<WeComponents />的形式，仅做局部控制，但尚未完整输出。请等待消息吧

**Comment by TonyLuo** [comment]
table 组件建议：
1、增加自定义pageSize，例如：attributes.pageSizes=[5,10,15,20]
2、 attributes.pagination 增加下拉选择pageSize，
3、增加onPageChange事件
4、增加onPageSizeChange事件

**Comment by TonyLuo** [comment]
我觉得这个项目的组件应该暴露出来，让开发人员灵活选择是否使用声明的方式进行组件渲染还是直接用传统的组件调用模式。

这个项目如果定位成是一个规范，一个中间层会不会更好些？现在很多vue ui组件比如iview，element ui等等，这个项目作为一个中间层，定义好规范，然后大家按照规范可以集成利用一些现有的轮子组件

**Comment by NaibinJi** [comment]
将在近期支持自定义组件能力，允许自定义组件并以声明的方式引入到业务页面中。复用性高的业务组件以及现有其他轮子组件，都可以通过自定义组件引入到业务中并进行使用。

**Comment by NaibinJi** [comment]
自定义组件已上线，使用方式详见https://tencent.github.io/WeComponents/#/components/basic/custom
