### ISSUE TITLE
是否考虑绑定响应式数据的api？

### ISSUE THREAD

**Issue by Rackar** [Tencent/WeComponents#4]
比如table容器，填充数据用：
this.page.setValue("list", tableValue);
数据变化之后还要再次执行一次。

是否考虑增加一个
setRespValue("list", tableValue);
监听tableValue值的变化，动态改变视图，回到数据绑定？

**Comment by damonpeng** [comment]
已经在下个大版本的规划中了，不谋而合的好提议。
