### ISSUE TITLE
是否支持项目中自定义组件

### ISSUE THREAD

**Issue by Yurunsoft** [Tencent/WeComponents#7]
如果通用组件无法满足业务需求时，希望可以自己编写组件并且引入。没有在文档中找到，不知道是否支持

**Comment by damonpeng** [comment]
感谢提议，确实刚需。我们将在下个大版本支持，如是通用需求，可以先邮件联系下我们。

**Comment by NaibinJi** [comment]
已在最新[提交](https://github.com/Tencent/WeComponents/commit/67fc864fa8842f73e27e8bf9cad98794773208cd)中支持
